"""Modbus protocol constants."""

# Function codes
READ_COILS = 0x01
READ_DISCRETE_INPUTS = 0x02
READ_HOLDING_REGISTERS = 0x03
READ_INPUT_REGISTERS = 0x04
WRITE_SINGLE_COIL = 0x05
WRITE_SINGLE_REGISTER = 0x06
WRITE_MULTIPLE_COILS = 0x0F
WRITE_MULTIPLE_REGISTERS = 0x10

# Default values
DEFAULT_TCP_PORT = 502
DEFAULT_UNIT_ID = 1
DEFAULT_TIMEOUT = 3.0
DEFAULT_BAUDRATE = 9600
DEFAULT_BYTESIZE = 8
DEFAULT_PARITY = "N"
DEFAULT_STOPBITS = 1

# Limits
MAX_REGISTER_COUNT = 125
MAX_COIL_COUNT = 2000
MAX_REGISTER_VALUE = 65535
MAX_ADDRESS = 65535
